!function(){function n(){var appleExpression=/Apple/i;var safariExpression=/Safari/i;var isSafari=(window.safari!==undefined)||(appleExpression.test(navigator.vendor)&&safariExpression.test(navigator.userAgent));if(isSafari){document.body.classList.add('isSafari');}
(function(){function window_media_cbk(e){if(e.matches){var menu=document.querySelector('.hdr-menu .main-menu');if(menu){var container=document.querySelector('.hdr-menu__mob');container.appendChild(menu);}}else{var menu=document.querySelector('.hdr-menu__mob .main-menu');if(menu){var container=document.querySelector('.hdr-menu');container.appendChild(menu);}}}
var window_mediaQuery=window.matchMedia('(max-width: 1135px)');window_mediaQuery.addListener(window_media_cbk);window_media_cbk(window_mediaQuery);}());(function(){function window_media_cbk(e){if(e.matches){(function(){var elem=document.querySelector('.ftr-social__cnt .ftr-social__inner');var container=document.querySelector('.ftr-menu__inner');if(elem&&container){container.insertAdjacentElement("afterend",elem);}}());}else{(function(){var elem=document.querySelector('footer > .cnt > .ftr-social__inner');var container=document.querySelector('.ftr-social__cnt');if(elem&&container){container.insertAdjacentElement("beforeend",elem);}}());}}
var window_mediaQuery=window.matchMedia('(max-width: 960px)');window_mediaQuery.addListener(window_media_cbk);window_media_cbk(window_mediaQuery);}());var hdr_height=0;var hdr_elem=document.querySelector('header');var hdr_preserve_elem=document.querySelector('#mainWrapper');function getHeaderHeight(onlyReturn){var onlyReturn=onlyReturn||false;var result=hdr_elem.offsetHeight;if(!onlyReturn){hdr_height=result;}
return result;}
getHeaderHeight();window.addEventListener('resize',function(){getHeaderHeight();});function checkHeaderStick(){var scroll=this.scrollY;if(scroll>hdr_height){document.body.classList.add('header-fixed');hdr_preserve_elem.style.paddingTop=hdr_height+'px';}else{document.body.classList.remove('header-fixed');hdr_preserve_elem.style.paddingTop='';}}
window.addEventListener('scroll',function(e){checkHeaderStick();});checkHeaderStick();window.addEventListener('scroll',function(e){document.documentElement.style.setProperty('--actual-header-height',getHeaderHeight(true)+'px');});document.querySelectorAll('.hdr__toggler').forEach(function(el){el.addEventListener('click',function(){document.documentElement.classList.toggle('mobmenu-active');});});document.querySelector('.hdr-menu__mob').addEventListener('click',function(e){var clickedLink=e.target.closest('a');if(clickedLink){document.documentElement.classList.remove('mobmenu-active');}});var urlHash=window.location.hash.split('?')[0];if(urlHash){scrollToHashElement(urlHash,70,10);}
function scrollToHashElement(hash,header,modifier,cbk){var debug=false;debug?console.log('hash СЂР°РІРµРЅ '+hash):'';var hash=hash.split('?')[0];var modifier=modifier||0;var hashElement=document.querySelector(hash);if(!hashElement){console.log(hashElement+' РЅРµ РЅР°Р№РґРµРЅ!');return true;}
header=header||document.querySelector('header')||0;if(header&&header instanceof Element){header=header.offsetHeight;}
var offsetTop=hashElement.getBoundingClientRect().top+document.documentElement.scrollTop-header-modifier;offsetTop=offsetTop.toFixed();if(debug){console.log('hashElement.getBoundingClientRect().top - РѕС‚СЃС‚СѓРї РѕС‚ РІРµСЂС…Р°',hashElement.getBoundingClientRect().top);console.log('document.documentElement.scrollTop - С‚РµРєСѓС‰РёР№ СЃРєСЂРѕР»Р»',document.documentElement.scrollTop);console.log('header - С…РµРґРµСЂ',header);console.log('modifier - РґРѕРї РѕС‚СЃС‚СѓРї',modifier);console.log('offsetTop - РёС‚РѕРіРѕ СЃРєСЂРѕР»Р»РёРј РґРѕ',offsetTop);}
if(cbk&&(typeof cbk==='function')){var scrollCbk=function(){if(window.pageYOffset.toFixed()===offsetTop){window.removeEventListener('scroll',scrollCbk)
cbk();}}
window.addEventListener('scroll',scrollCbk);}
window.scrollTo({top:offsetTop,behavior:'smooth',});}
document.body.addEventListener('click',function(e){var el=e.target.closest('a[href*="#"]');if(el){if(location.pathname.replace(/^\//,'')===el.pathname.replace(/^\//,'')&&location.hostname===el.hostname){var path=el.getAttribute('href').replace(location.pathname,'').split('?')[0];if(path!=='#'){if(document.querySelector(path)){e.preventDefault();scrollToHashElement(path,70,30);}else{console.log(path+' РЅРµ РЅР°Р№РґРµРЅ!',path);}}}}});if(window['Swiper']){var offers_slider__elem=document.querySelector('.offers-slider__inner');if(offers_slider__elem){var offers_slider=new Swiper(offers_slider__elem,{slideClass:'sld',wrapperClass:'slider',a11y:{enabled:false,},loop:false,slidesPerView:'auto',loopAdditionalSlides:1,});}
var reviews_slider__elem=document.querySelector('.reviews-list__wrapper');if(reviews_slider__elem){var reviews_slider=new Swiper(reviews_slider__elem,{slideClass:'sld',wrapperClass:'slider',a11y:{enabled:false,},loop:false,slidesPerView:'auto',loopAdditionalSlides:1,});}}
setTimeout(function(){document.querySelectorAll('.modal_form').forEach(function(el,ind){el.style.marginTop='-'+(el.offsetHeight/2)+'px';});},500);function showWebform(wfId){document.body.classList.add('modal_active');document.querySelector('.modal_overlay').classList.add('visible');var wf=document.querySelector(wfId);if(wf){wf.classList.add('visible');wf.style.marginTop='-'+(wf.offsetHeight/2)+'px';}}
function closeWebform(){document.body.classList.remove('modal_active');document.querySelectorAll('.modal_overlay, .modal_form').forEach(function(el,ind){el.classList.remove('visible');});}
document.querySelectorAll('.modal_overlay, .modal_close').forEach(function(el){el.addEventListener('click',function(e){closeWebform();e.currentTarget.classList.remove('sent');});});document.querySelectorAll('.trigger[data-modal]').forEach(function(el){el.addEventListener('click',function(){var id=el.getAttribute('data-modal');showWebform('#'+id);});});document.querySelectorAll('.tabs__wrapper').forEach(function(el,ind){var debug=false;var tabs__root=el;var tabs__list=tabs__root.querySelector('.tabs__tablist');var tabs__contentWrap=tabs__root.querySelector('.tabs__content--wrapper');if(!tabs__list||!tabs__contentWrap){if(debug)console.log('tabs: РЅРµ РЅР°Р№РґРµРЅ .tabs__list РёР»Рё .tabs__contentWrap',tabs__list,tabs__contentWrap);return false;}
tabs__root.addEventListener('click',function(e){var tab=e.target.closest('.tabs__tab');if(!tab){if(debug)console.log('tabs: РєР»РёРє РїРѕ С‚Р°Р±Сѓ, РЅРѕ РЅРµ РЅР°С€Р»Рё СЃР°Рј СЌР»РµРјРµРЅС‚-СѓРєР°Р·Р°С‚РµР»СЊ',e.target);return false;}
if(tab.classList.contains('active'))return false;var target_id=tab.dataset.tab;if(!target_id){if(debug)console.log('tabs: target_id (data-tab) РїСѓСЃС‚!',tab);}
var target_elem=tabs__contentWrap.querySelector('.tabs__tabcontent[data-tab="'+target_id+'"]');if(!target_elem){if(debug){console.log('tabs: С†РµР»РµРІРѕРіРѕ СЌР»РµРјРµРЅС‚Р° СЃ РєРѕРЅС‚РµРЅС‚РѕРј РЅРµ СЃСѓС‰РµСЃС‚РІСѓРµС‚ ( .tabs__tabcontent[data-tab="'+target_id+'"] )',target_elem);}
return false;}
tabs__root.querySelectorAll('.active').forEach(function(actElem){if((actElem!=tab)&&(actElem!=target_elem))actElem.classList.remove('active');});tab.classList.add('active');target_elem.classList.add('active');});});document.querySelectorAll('.spoiler__heading').forEach(function(el){el.addEventListener('click',function(e){var parent=e.target.closest('.spoiler__item');if(parent)parent.classList.toggle('opened');});});if(window['vanillaTextMask']){document.querySelectorAll('input[type="tel"], input[name="phn"]').forEach(function(el,ind){var maskedInputController=vanillaTextMask.maskInput({inputElement:el,mask:['+','7',' ','(',/\d/,/\d/,/\d/,')',' ',/\d/,/\d/,/\d/,'-',/\d/,/\d/,'-',/\d/,/\d/],guide:false});el.addEventListener('keyup',function(e){var val=e.target.value;e.target.value=val.replace(/^\+7 \([7-8]([8-9])/,"+7 ($1");});el.value='';});}
document.querySelectorAll('input[name="furl"]').forEach(function(el){el.value=window.location.href});document.querySelectorAll('input[name="fh1"]').forEach(function(el){var h1=document.querySelector('h1');if(h1){h1=h1.textContent;}else{h1=document.title;}
el.value=h1;});document.querySelectorAll('.form__inner .acceptance .accept-label').forEach(function(el){el.addEventListener('click',function(e){if(e.target.tagName==='A')return false;var parent=e.currentTarget.closest('.acceptance');if(!parent)return false;var checkbox=parent.querySelector('input[type="checkbox"]');if(!checkbox)return false;checkbox.checked^=1;});});document.querySelectorAll('.cf7-custom-select__first-option').forEach(function(el){el.addEventListener('click',function(e){e.currentTarget.classList.toggle('opened');});});document.querySelectorAll('.cf7-custom-select__option').forEach(function(el){el.addEventListener('click',function(e){var itemWrapper=e.currentTarget.closest('.item');if(!itemWrapper){console.log('cf7-custom-select: Р РѕРґРёС‚РµР»СЊ РЅРµ РЅР°Р№РґРµРЅ!');return false;}
var targetInput=itemWrapper.querySelector('input[type="text"]');if(!targetInput){console.log('cf7-custom-select: Р¦РµР»РµРІРѕР№ РёРЅРїСѓС‚ РЅРµ РЅР°Р№РґРµРЅ!');return false;}
var firstOption=itemWrapper.querySelector('.cf7-custom-select__first-option');var value=e.currentTarget.textContent.trim();targetInput.value=value;if(firstOption)firstOption.textContent=value;var documentLink=e.currentTarget.getAttribute('data-document');if(documentLink){var documentLinkTarget=e.currentTarget.closest('form').querySelector('.item.acceptance a.contract');if(documentLinkTarget){documentLinkTarget.href=documentLink;}}
var prodId=e.currentTarget.getAttribute('data-id')||0;var prodIdInput=e.currentTarget.closest('form').querySelector('input.prod-id');if(prodIdInput)prodIdInput.value=prodId;if(firstOption)firstOption.classList.toggle('opened');var row=e.currentTarget.closest('.cf7-custom-select__row');if(row)row.classList.remove('not-valid');});});document.querySelectorAll('.cf7-custom-select__row input[type="text"]').forEach(function(el){var observer=new MutationObserver(function(mutationsList,observer){mutationsList.forEach(function(record){if(record.type==='attributes'){if(record.target){var parent=record.target.closest('.cf7-custom-select__row');if(parent&&(record.target.classList.contains('wpcf7-not-valid'))){parent.classList.add('not-valid');}else if(parent&&!(record.target.classList.contains('wpcf7-not-valid'))){parent.classList.remove('not-valid');}}}});});observer.observe(el,{attributes:true,characterDataOldValue:true});});document.querySelectorAll('.cf7-custom-select__row .cf7-custom-select__option.default').forEach(function(el){var parent=el.closest('form');if(!parent)return false;var val=el.textContent.trim();var input=parent.querySelector('.cf7-custom-select__row input[name="product"]');if(input)input.value=val;var label=parent.querySelector('.cf7-custom-select__row .cf7-custom-select__first-option');if(label)label.textContent=val;var contract=parent.querySelector('.item.acceptance a.contract');var documentLink=el.getAttribute('data-document');if(contract&&documentLink)contract.href=documentLink;var prodIdInput=parent.querySelector('input.prod-id');var prodId=el.getAttribute('data-id')||0;if(prodIdInput)prodIdInput.value=prodId;});document.querySelectorAll('.form__inner .row.acceptance-row input[type=checkbox][name="accept[]"], .form__inner .row.acceptance-row input[type=checkbox][name="messaging[]"]').forEach(function(el){el.checked=true;});document.querySelectorAll('form.wpcf7-form').forEach(function(el){var observer=new MutationObserver(function(mutationsList,observer){mutationsList.forEach(function(record){if(record.type==='attributes'){if(record.target){var parent=record.target.closest('.modal_form');if(parent&&(record.target.classList.contains('sent'))){parent.classList.add('sent');}else if(parent&&!(record.target.classList.contains('sent'))){parent.classList.remove('sent');}}}});});observer.observe(el,{attributes:true,characterDataOldValue:true});});document.querySelectorAll('form.wpcf7-form input[type="text"], form.wpcf7-form textarea').forEach(function(el){el.addEventListener('change',function(e){if(this.value){this.classList.add('filled');}else{this.classList.remove('filled');}});});document.querySelectorAll('.trigger[data-modal]').forEach(function(el){if(window['defaultContract_'+el.dataset.modal.replace('-','_')]==undefined){var contractElem=document.querySelector('#'+el.dataset.modal+' .item.acceptance a.contract');if(contractElem){window['defaultContract_'+el.dataset.modal.replace('-','_')]=contractElem.href;}}
el.addEventListener('click',function(e){var contractElem=document.querySelector('#'+e.currentTarget.dataset.modal+' .item.acceptance a.contract');if(contractElem&&(window['defaultContract_'+e.currentTarget.dataset.modal.replace('-','_')])){contractElem.href=window['defaultContract_'+e.currentTarget.dataset.modal.replace('-','_')];}
var productID=document.querySelector('#'+e.currentTarget.dataset.modal+' input.prod-id');if(productID)productID.value='';});});document.querySelectorAll('.products__block .btn.trigger[data-modal]').forEach(function(el){el.addEventListener('click',function(e){var wrapper=e.currentTarget.closest('.inner');if(!wrapper)return false;docLink=wrapper.getAttribute('data-document');var prodName=wrapper.getAttribute('data-popupname')||'';if(prodName){prodName=prodName.trim();}else{prodName=wrapper.querySelector('.products__name');if(prodName){prodName=prodName.textContent.trim();}else{prodName='';}}
var prodid=wrapper.getAttribute('data-id')||0;document.querySelectorAll('#'+el.dataset.modal+' .item.acceptance a.contract').forEach(function(elem){elem.href=docLink;});document.querySelectorAll('#'+el.dataset.modal+' .cf7-custom-select__row input[name="product"]').forEach(function(elem){elem.value=prodName;});document.querySelectorAll('#'+el.dataset.modal+' .cf7-custom-select__row .cf7-custom-select__first-option').forEach(function(elem){elem.textContent=prodName;});document.querySelectorAll('#'+e.currentTarget.dataset.modal+' input.prod-id').forEach(function(elem){elem.value=prodid;});});});(function(){document.querySelectorAll('#mainWrapper a, .modals a, .mobmenu a').forEach(function(el){var href=el.getAttribute('href');if(href.indexOf('#')===0)return false;el.setAttribute('href',el.getAttribute('href')+window.location.search)});}());}"loading"!=document.readyState?n():document.addEventListener("DOMContentLoaded",function(){n()})}();